-- Clear remaining transactional/test state while preserving production setup.
--
-- Preserves:
--   - auth users
--   - hotels, offerings, rooms, amenities
--   - staff and role/config tables
--   - storage buckets/objects
--
-- Clears:
--   - bookings and booking-derived rows
--   - payments, settlements, payouts, refunds, disputes
--   - financial ledgers/components generated by test transactions
--   - payment logs/webhook/reconciliation events
--   - cached AzamPay tokens
--
-- Blocked by default. Execute intentionally with:
--
--   psql "$PRODUCTION_DB_URL" -v ON_ERROR_STOP=1 -v execute_cleanup=true -f supabase/maintenance/production_cleanup_transactional_state.sql

\if :{?execute_cleanup}
\else
\set execute_cleanup false
\endif

\if :execute_cleanup
\echo 'Transactional cleanup enabled. Proceeding inside one transaction.'
\else
\echo 'Refusing to clear transactional state. Re-run with -v execute_cleanup=true after confirming production cleanup intent.'
select 1 / 0 as cleanup_guard_error;
\endif

begin;
set local role postgres;
set local session_replication_role = replica;
set local statement_timeout = '60s';
set local lock_timeout = '10s';

select 'before_bookings' as bucket, count(*) as rows from public.bookings
union all select 'before_booking_items', count(*) from public.booking_items
union all select 'before_payments', count(*) from public.payments
union all select 'before_settlements', count(*) from public.settlements
union all select 'before_ledger_entries', count(*) from public.ledger_entries
union all select 'before_financial_components', count(*) from public.financial_components
union all select 'before_financial_ledger', count(*) from public.financial_ledger
union all select 'before_payment_logs', count(*) from public.payment_logs
union all select 'before_payment_webhook_events', count(*) from public.payment_webhook_events
union all select 'before_payment_reconciliation_events', count(*) from public.payment_reconciliation_events
union all select 'before_payout_batches', count(*) from public.payout_batches
union all select 'before_payout_items', count(*) from public.payout_items
union all select 'before_payout_provider_events', count(*) from public.payout_provider_events
union all select 'before_refunds', count(*) from public.refunds
union all select 'before_disputes', count(*) from public.disputes
union all select 'before_reviews', count(*) from public.reviews
union all select 'before_room_statuses_linked_to_bookings', count(*) from public.room_statuses where booking_id is not null
union all select 'before_azampay_tokens', count(*) from public.azampay_tokens
order by bucket;

delete from public.payout_provider_events;
delete from public.payout_items;
delete from public.payout_batches;
delete from public.payment_reconciliation_events;
delete from public.payment_webhook_events;
delete from public.payment_logs;
delete from public.financial_components;
delete from public.ledger_entries;
delete from public.financial_ledger;
delete from public.refunds;
delete from public.disputes;
delete from public.reviews;
delete from public.room_statuses where booking_id is not null;
delete from public.settlements;
delete from public.booking_item_financials;
delete from public.booking_items;
delete from public.payments;
delete from public.bookings;
delete from public.azampay_tokens;

select 'after_bookings' as bucket, count(*) as rows from public.bookings
union all select 'after_booking_items', count(*) from public.booking_items
union all select 'after_payments', count(*) from public.payments
union all select 'after_settlements', count(*) from public.settlements
union all select 'after_ledger_entries', count(*) from public.ledger_entries
union all select 'after_financial_components', count(*) from public.financial_components
union all select 'after_financial_ledger', count(*) from public.financial_ledger
union all select 'after_payment_logs', count(*) from public.payment_logs
union all select 'after_payment_webhook_events', count(*) from public.payment_webhook_events
union all select 'after_payment_reconciliation_events', count(*) from public.payment_reconciliation_events
union all select 'after_payout_batches', count(*) from public.payout_batches
union all select 'after_payout_items', count(*) from public.payout_items
union all select 'after_payout_provider_events', count(*) from public.payout_provider_events
union all select 'after_refunds', count(*) from public.refunds
union all select 'after_disputes', count(*) from public.disputes
union all select 'after_reviews', count(*) from public.reviews
union all select 'after_room_statuses_linked_to_bookings', count(*) from public.room_statuses where booking_id is not null
union all select 'after_azampay_tokens', count(*) from public.azampay_tokens
order by bucket;

commit;
